# Generated by Django 6.0.2 on 2026-03-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_application_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ats_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
